root | DEBUG | 2020-11-24 11:58:57,566 | Number of records: 29
root | DEBUG | 2020-11-24 11:59:10,733 | Number of records: 29
root | ERROR | 2020-11-24 11:59:14,091 | Exception occurred due to wrong file path
Traceback (most recent call last):
  File "/Users/nusrat/PycharmProjects/census_analyser_project/main/census_analyser.py", line 53, in load_census_data
    self.validate_csv(csv_file_path)
  File "/Users/nusrat/PycharmProjects/census_analyser_project/main/census_analyser.py", line 13, in validate_csv
    self.validate_delimiter(csv_file_path)
  File "/Users/nusrat/PycharmProjects/census_analyser_project/main/census_analyser.py", line 21, in validate_delimiter
    with open(csv_file_path, newline="") as csv_data:
FileNotFoundError: [Errno 2] No such file or directory: 'rmain/IndiaStateCensusData.csv'
root | ERROR | 2020-11-24 11:59:14,101 | Exception occurred due to wrong file extension
NoneType: None
root | ERROR | 2020-11-24 11:59:14,114 | Exception occurred due to improper delimiter
Traceback (most recent call last):
  File "/Users/nusrat/PycharmProjects/census_analyser_project/main/census_analyser.py", line 23, in validate_delimiter
    csv.Sniffer().sniff(csv_data.read(), delimiters=",")
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/csv.py", line 187, in sniff
    raise Error("Could not determine delimiter")
_csv.Error: Could not determine delimiter
root | ERROR | 2020-11-24 11:59:14,126 | Exception occurred due to improper header
NoneType: None
root | DEBUG | 2020-11-24 11:59:16,014 | Number of records: 37
root | ERROR | 2020-11-24 11:59:19,617 | Exception occurred due to improper header
NoneType: None
root | ERROR | 2020-11-24 11:59:19,623 | Exception occurred due to improper delimiter
Traceback (most recent call last):
  File "/Users/nusrat/PycharmProjects/census_analyser_project/main/census_analyser.py", line 23, in validate_delimiter
    csv.Sniffer().sniff(csv_data.read(), delimiters=",")
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/csv.py", line 187, in sniff
    raise Error("Could not determine delimiter")
_csv.Error: Could not determine delimiter
root | ERROR | 2020-11-24 11:59:19,634 | Exception occurred due to wrong file path
Traceback (most recent call last):
  File "/Users/nusrat/PycharmProjects/census_analyser_project/main/census_analyser.py", line 53, in load_census_data
    self.validate_csv(csv_file_path)
  File "/Users/nusrat/PycharmProjects/census_analyser_project/main/census_analyser.py", line 13, in validate_csv
    self.validate_delimiter(csv_file_path)
  File "/Users/nusrat/PycharmProjects/census_analyser_project/main/census_analyser.py", line 21, in validate_delimiter
    with open(csv_file_path, newline="") as csv_data:
FileNotFoundError: [Errno 2] No such file or directory: 'project/main/IndianStateCode.csv'
root | ERROR | 2020-11-24 11:59:19,640 | Exception occurred due to wrong file extension
NoneType: None
root | DEBUG | 2020-11-24 11:59:24,765 | Number of records: 29
root | DEBUG | 2020-11-24 11:59:24,765 | start state and end state: Andhra Pradesh West Bengal
root | DEBUG | 2020-11-24 11:59:26,678 | Number of records: 29
root | DEBUG | 2020-11-24 11:59:26,679 | start state and end state: Andhra Pradesh West Bengal
root | DEBUG | 2020-11-24 11:59:28,598 | Number of records: 37
root | DEBUG | 2020-11-24 11:59:28,598 | start state and end state : AD WB
root | DEBUG | 2020-11-24 11:59:30,477 | Number of records: 37
root | DEBUG | 2020-11-24 11:59:30,479 | start state and end state : AD WB
root | DEBUG | 2020-11-24 11:59:32,149 | Number of records: 29
root | DEBUG | 2020-11-24 11:59:32,150 | most populous state: 199812341
root | DEBUG | 2020-11-24 11:59:33,807 | Number of records: 29
root | DEBUG | 2020-11-24 11:59:33,808 | most densely populous state: 1102
root | DEBUG | 2020-11-24 11:59:36,665 | Number of records: 29
root | DEBUG | 2020-11-24 11:59:36,666 | largest area state: 342239
